services:
  web:
    build:
      context: .
      target: development
    ports:
      - "4567:4567"
      - "9394:9394"
    volumes:
      - .:/app
    env_file:
      - .env
      - env.development
    command:
      - bundle
      - exec
      - rackup
      - -p
      - "4567"
      - --host
      - 0.0.0.0
  css:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    command: bundle exec ruby ./config/css-listener.rb
  js:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    command: bundle exec ruby ./config/js-listener.rb
