name: Run Tests

on: push

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Create .env file
        run: cat env.* > .env
      - name: Load .env file
        uses: xom9ikk/dotenv@d0a56edc74279820eabbe34477511327e710d0de # v2.4.0
      - name: Set up Ruby 4.0
        uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
        with:
          ruby-version: '4.0'
          bundler-cache: true
        env: 
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ secrets.GITHUB_TOKEN }}
      - name: Run linter for Ruby
        run: bundle exec standardrb
      - name: Run tests
        run: bundle exec rspec
