name: Update Closed Days

on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 8 1 * *' #8AM first of the month

jobs:
  update-closed-days:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Create .env file
        run: cat env.* > .env
      - name: Load .env file
        uses: xom9ikk/dotenv@ac290ca23a42155a0cba1031d23afa46240116a9 # v2.3.0
      - name: Set up Ruby 4.0
        uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
        with:
          ruby-version: '4.0'
          bundler-cache: true
        env: 
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ secrets.GITHUB_TOKEN }}
      - name: update closed days
        env:
          ALMA_API_KEY: ${{ secrets.ALMA_API_KEY }}
        run: bundle exec ruby bin/update_alma_config.rb
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0

        with: 
          branch: update-closed-days
          commit-message: "Update closed days"
          title: "Update closed days" 
          reviewers: niquerio, erinesullivan
